version: '3.8'

services:
  themeparkql.server:
    build:
      context: .
      dockerfile: ThemeparkQL.Server/Dockerfile
    container_name: themeparkQL Server
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - themeparkql.database
  themeparkql.database:
    image: postgres:latest
    container_name: themeparkQL Database
    environment:
      - POSTGRES_DB=themeparkql
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/themeparkql-database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
